### ISSUE TITLE
on safari i get these strange symbols

### ISSUE THREAD

**Issue by dtaliun** [statgen/pheweb#106]
![screenshot 2018-03-21 08 36 26](https://user-images.githubusercontent.com/12834564/37710157-30e2a1e2-2ce3-11e8-8cb4-8d410d3fe801.png)

**Comment by sgagliano** [comment]
In which instance of PheWeb are you seeing this?
For me, the square symbols in your screenshot in front of "Previous" and after "Next" correctly appear as arrows on Safari for the SAIGE UKBB PheWeb.

**Comment by dtaliun** [comment]
http://pheweb.sph.umich.edu:5003

**Comment by dtaliun** [comment]
404 for the following:
![screenshot 2018-03-21 09 12 07](https://user-images.githubusercontent.com/12834564/37711745-1b03be06-2ce8-11e8-835a-6ba58bc245dc.png)

**Comment by pjvandehaar** [comment]
My Safari (`Version 11.0.3 (12604.5.6.1.1)`) doesn't have this problem.  I think you have an old Safari.  I'll fix this.

**Comment by pjvandehaar** [comment]
Bootstrap requires:

**Comment by pjvandehaar** [comment]
This should be fixed now on <http://pheweb.org/UKBiobank>.  I'll roll the fix out to the others later.
