### ISSUE TITLE
RESTful API specs

### ISSUE THREAD

**Issue by phuwanat** [statgen/pheweb#107]
Hi,

Is there a doc on available API requests available for UK biobank's pheweb? Thank you!

**Comment by pjvandehaar** [comment]
No documentation is available right now, and I'm not making any guarantees that the current API (used by the site itself) will be preserved, but I don't have plans to change it much soon.

What are you looking to do?

**Comment by phuwanat** [comment]
I would like to query hits (phenotypes and corresponding p values) for a
set of SNPs. If so, I could try looking through the code. Thank you very
much.

On Mar 23, 2018 2:47 AM, "Peter VandeHaar" <notifications@github.com> wrote:

No documentation is available right now, and I'm not making any guarantees
that the current API (used by the site itself) will be preserved, but I
don't have plans to change it much soon.

What are you looking to do?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/statgen/pheweb/issues/107#issuecomment-375560650>, or mute
the thread

**Comment by pjvandehaar** [comment]
- How many SNPs? (ie, tens, hundreds, thousands, ten-thousands?)
- Is this a one-time use, or are you interested in doing this a lot?

Here's a `curl` command to get json for a variant. Please don't run it more than 1000 times, and not more than once per second (eg, add `sleep 1` in your script).  This might break at any time when I change PheWeb, but it won't break in the next 48 hours.

```
curl --silent 'http://pheweb.sph.umich.edu:5003/variant/6-26123502-T-C' | grep 'window.variant =' | perl -pale 's/^.*?{/{/; s{;$}{}'
```

**Comment by phuwanat** [comment]
My plan is ~ 200 SNPs and would be one time (for this paper : )

Thank you very much

Sent from Mail for Windows 10

**Comment by pjvandehaar** [comment]
Try this URL instead of the `curl`-based approach: <http://pheweb.sph.umich.edu:5003/api/variant/6-32879471-A-G>

**Comment by phuwanat** [comment]
Thanks! This is very helpful.

Sent from Mail for Windows 10
