### ISSUE TITLE
Support build 38

### ISSUE THREAD

**Issue by pjvandehaar** [statgen/pheweb#113]
- [x] allow the user to set the build in `config.py`.
    - For now, just set `build = '38'` in `config.py`, and leave it undocumented so we can change it.
    - Later: I wish that build and fields were more explicit.  For association-file-parsing, I'd prefer to auto-generate the parser config and write it to `./generated-by-pheweb/parser-config.json`.  Build should go with it.  Tooltip config, though closely related, should probably go somewhere else.
- [x] Use the appropriate gencode and dbsnp.
    - Files affected: `<cache>/gene_aliases.marisa_trie` `<cache>/genes-27.bed` `<cache>/rsids-150.vcf.gz` and several temp files
    - [ ] We could make `file_utils.common_filepaths['genes']` magically handle the version.  Sure, sounds interesting, do it.
    - [ ] Download gencode from `ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_28/`, and set `file_utils.genes_version = '28'`.  In theory this could be different for different builds, but for now it's the same so don't bother `dict`ing it.
    - [ ] Make sure the gencode parser works for both builds.
    - [ ] Download dbsnp from `ftp://ftp.ncbi.nlm.nih.gov/snp/organisms/human_9606_b151_GRCh37p13/VCF/` and `ftp://ftp.ncbi.nlm.nih.gov/snp/organisms/human_9606_b151_GRCh38p7/VCF/`.  Set `file_utils.dbsnp_version = '151'.  Make `pheweb.load.download_rsids` deal with the URL difference.
    - [ ] Make sure the dbsnp parser works for both builds.
- [x] Javascript: Set `window.model.genome_build`.  Adjust LZ's datasources for LD, recombination rates, and genes.
    - [ ] Ask the appropriate people where to get these data.
    - [ ] For genes, perhaps each pheweb should just use its own local API.
    - [ ] Once this works, remove `window.model.genome_build` and instead directly pass it to each function that needs it.
- [x] Jinja: show the build on the about page.

**Comment by abought** [comment]
For LZ datasources, see discussion on the #Locuszoom channel in our slack today. Basically:

- Genes already have build 38 data
- There is a path to LD data, which we should coordinate with Daniel (LD server) and Ryan (portal API integration) when Daniel gets back
- Surprisingly, recombination rates lack a modern dataset; liftover may be an option

If you haven't looked at the required LZ updates yet, feel free to create a ticket in that repo and assign me as help needed. We can discuss this (and GWAS catalog) tomorrow.

**Comment by abought** [comment]
Adding relevant PR link:
https://github.com/statgen/locuszoom/pull/149

This PR will add LD and gene support for h38. It's a work in progress, as we're still beta testing the new LD server a bit (see checklist for plans and future directions).

**Comment by abought** [comment]
For the Locuszoom side of this task:

Build 38 support has been merged into LZ.js `develop` branch, including use of new LD and Recomb rate API data. (thanks, Ryan and Daniel!) Gene data was already available.

If you specify `genome_build: 'GRCh38'` in `plot.state`, all LZ.js data sources will automatically choose a dataset appropriate to that build. Would this help reduce the amount of custom code needed for your configuration?

Here is an example showing what that looks like (notice that most sources no longer encode a `source:` value of their own)
https://github.com/statgen/locuszoom/blob/develop/examples/gwas_catalog.html#L86-L111

**Comment by kuulasmaa** [comment]
Is there any progress on this front? Any schedule when hg38 support might be available? PheWeb is excellent project and I would be glad to see hg38 to be supported in the future. Unfortunately I am not able to contribute to code but I am more than happy to test it.

**Comment by abought** [comment]
To help track work and blockers: the separate genelocator package handles build38 .

I've also got some RSID parsers that operate on the new DB snp build 153 format, for both genome builds 37 and 38. Let me know what would be useful to get this moving.
