### ISSUE TITLE
Remove python version restriction

### ISSUE THREAD

**Issue by abought** [statgen/pheweb#122]
PheWeb contains a hard-coded exception in its setup script to prevent installation with Python 3.7, but this no longer appears to be necessary when using newer Pysam releases.
https://github.com/statgen/pheweb/blob/master/setup.py#L14

Leaving this issue here as a reminder to revisit this restriction in the future. My own work will target Python 3.6, so not a blocker for now.

(discovered only because I toggled the wrong setting in pyenv, while using pheweb as a library of code)

**Comment by pjvandehaar** [comment]
Thanks for pointing this out.  Addressed in https://github.com/statgen/pheweb/commit/e5e6486 .
