### ISSUE TITLE
use SGE for multiprocessing

### ISSUE THREAD

**Issue by dl016d** [statgen/pheweb#125]
Is it possible to add support for Sun Grid Engine (SGE) cluster scheduler?

**Comment by pjvandehaar** [comment]
Definitely.  See
https://github.com/statgen/pheweb#5-load-your-association-files .
Converting the `pheweb slurm-parse` to work on SGE should be trivial.  If
you make the changes, I'd appreciate it if you'd send them to me and I
could incorporate them into PheWeb.  If you're looking to use SGE on the
rest of the loading steps, it will take a little more work, but not a lot
more.  I think that effort would be better spent on speeding up the reader
and writer for the internal files (perhaps using Pandas), but I'm happy to
give you advice on how to add SGE support as well.

Peter

**Comment by figueroakl** [comment]
If possible it would be great to have some advice on using SGE on the rest of the loading steps. So far, I have successfully adapted the slurm-parse script to SGE :

#!/bin/bash
#$ -t 1-20 
#$ -l h_vmem=4G
#$ -l h_rt=04:00:00
#$ -N parse_taskarrays
#$ -cwd
#$ -o stdout/logs/
#$ -e stderr/logs/

source /broad/software/scripts/useuse
use .python-3.8.3

now=$(date)

jobs=($(seq 0 19))

export PHEWEB_DATADIR='/humgen/florezlab/kfiguero/20_pheno_chr22_parallel'

echo "Pheweb parsing is starting at : ${now}"
/home/unix/kfiguero/.local/bin/pheweb conf num_procs=4 parse --phenos=${jobs[($SGE_TASK_ID - 1)]}
echo "Pheweb parsing has ended at : ${now}"

**Comment by pjvandehaar** [comment]
On the branch `hg38` I added a `--phenos=1,3,5-8` option to all of the one-task-per-pheno processing steps.  I want to test that branch a little more before I merge it into `master` and release it, but it all seems to work right now.  If you update to that release you'll be able to easily adapt your script to run more of the processing steps.

**Comment by pjvandehaar** [comment]
I just released version `1.1.28` which allows `pheweb cluster --engine=[slurm|sge] --step=[parse|augment-phenos|bgzip-phenos|manhattan|qq]`.
