### ISSUE TITLE
Fold LZ y-axis

### ISSUE THREAD

**Issue by pjvandehaar** [statgen/pheweb#127]
Currently I turn pval=0 into pval=1e-100, resulting in 
![image](https://user-images.githubusercontent.com/862089/65449991-2a2ad480-de0a-11e9-9564-5f92ecc9d35b.png).

Worst option: use 1e-323 instead
Better option: show pval=0 above a little margin
Best option: add variable `"fold_yaxis_at_20": true` in panel layout which disallows custom ticks and y-axis-dragging

**Comment by ttbek** [comment]
Hmm, what about plotting zeros at y=-1?  Unintuitive because that direction is less signifiant (down on the plot), but it may be easier to implement and would make them stand out.  Or perhaps plot them on a separate track above.

**Comment by pjvandehaar** [comment]
Right now pval=0 is plotting as pval=1e-323.  I think that's better than -1.

Sometime if I implement y-axis-folding (like the manhattan plot's y-axis), making the separate track for pval=0 associations will be easy.
