### ISSUE TITLE
pip3 install pheweb fails in official Python 3.8 docker image

### ISSUE THREAD

**Issue by huy-nguyen** [statgen/pheweb#129]
Steps to reproduce:

- Run the official python 3.8 container by issuing the command `docker run --rm -ti python:3.8.0 /bin/bash`
- Inside the Docker container, run `pip3 install pheweb`. It fails with the attached log file.
[log.txt](https://github.com/statgen/pheweb/files/3887614/log.txt). Essentially the failure happens here 
```
error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pysam
```
I've tried the more detailed installation instructions but got the same errors.
Here's the info on the Docker image's Linux distribution:
```
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by huy-nguyen** [comment]
This seems related to https://github.com/pysam-developers/pysam/issues/860 because installing `pheweb` works fine on python 3.7.

**Comment by pjvandehaar** [comment]
The same error happened when python 3.7 was released.  The pysam devs need a couple weeks to update.  I'll see about a workaround.

**Comment by pjvandehaar** [comment]
For now, run

```
pip3 install -U cython
pip3 install https://github.com/pysam-developers/pysam/archive/master.zip
pip3 install pheweb
```

And let me know whether that works.

**Comment by huy-nguyen** [comment]
Thanks. Your quick fix works. I think it's worth adding these notes to the documentation so that newcomers are not stumped every time a new Python version is released.

**Comment by pjvandehaar** [comment]
That's a good suggestion.  Instructions are in the "detailed install instructions" linked from https://github.com/statgen/pheweb#1-install-pheweb .
