### ISSUE TITLE
update HTML from about page

### ISSUE THREAD

**Issue by anasanchezlucas** [statgen/pheweb#131]
Good afternoon, I'm trying to customize the About page on my Pheweb. I have made my own version of about/content.html based on the template and it's not working. The old text is still appearing.Do I have to modify any other file? I have tried to run everything from scratch and it doesn't work either. 

Any help would be appreciated. 

Thank you

Ana

**Comment by pjvandehaar** [comment]
Thanks for asking.  I need to document this better.

```
┣ generated-by-pheweb/
┗ custom_templates/
   ┗ about/
      ┗ content.html
```

`content.html` should just be the content you want to show, like 

```
<p>Results displayed in this PheWeb include genome-wide associations for EHR-derived ICD billing codes from the White British participants of the UK Biobank. Phenotypes were classified into 1,403 broad PheWAS codes with counts ranging from 51 – 77,977 cases and 330,366 – 408,908 controls. All individuals were imputed using the Haplotype Reference Consortium panel, resulting in >20 million variants. Analyses on binary outcomes were conducted using SAIGE (a generalized mixed model association test that uses the saddlepoint approximation to account for case-control imbalance), adjusting for genetic relatedness, sex, birth year and the first 4 principal components. All genomic positions are on GRCh37.</p>

<p>This site was built with <a href="https://github.com/statgen/pheweb/">PheWeb</a> version {{ config.PHEWEB_VERSION }}.</p>

```

**Comment by anasanchezlucas** [comment]
Thank you, we have solved the problem.
We had the custom_templates folder in the wrong place, by taking it out to our directory layout now is working!

Best regards,

Ana

**Comment by pjvandehaar** [comment]
I'm glad it's working for you!  Feel free to open an issue or email me if you have other questions about PheWeb.
