### ISSUE TITLE
Public the website

### ISSUE THREAD

**Issue by stat-yyang** [statgen/pheweb#132]
Hi, 

Thanks a lot for your contributions to the Pheweb project. It's amazing to see the results displayed on a website.
I am quite new to web development. I am exploring to deploy the website built locally to the public.
Now I have followed all the steps in your instructions and served the website in a cluster and I can access it using my own computer. However, I would like to make it public and allow everyone to access it.

Do you know any methods to achieve that? Please just briefly give me some guidance and I can explore furthermore.

Thanks!

**Comment by pjvandehaar** [comment]
That's great, I'm glad it works well for you.  How do you access the site on your computer?  Can you reach it from anywhere, using an IP address?  Or only at your office?  Or did you have to do SSH tunneling?

If you don't have one, you need a computer in your cluster that accepts connections on port 80 from the open internet.  If that's not possible, AWS or DigitalOcean work great.

There's more info at https://github.com/statgen/pheweb#6-serve-the-website .  If you haven't used Apache2 before, read a guide like [this one](https://www.digitalocean.com/community/tutorials/how-to-install-the-apache-web-server-on-ubuntu-18-04).

I'd love to see your site once it's public.

**Comment by stat-yyang** [comment]
Thanks for your advice! We were going to serve it using the School server but was told that it only accepted internal access. Do you have any advice on which cloud computing service to buy? 

Basically, do we need a computer running all the time or could we publish all of the generated files to a host?

**Comment by pjvandehaar** [comment]
I recommend a webserver. If you prevented scrolling and zooming the Locuszoom region plots and limited the autocomplete search box to only show genre names and phenotypes (and no longer show rsids or variants), the site could be converted to static files using wget or a dedicated archiving tool. It would take a lot more storage space then.  I expect that it would take me a day to do. If you want to attempt it I can offer advice on implementing the 3 changes I listed above.

**Comment by stat-yyang** [comment]
Thank you so much! This is exactly what I am looking for (using static files and deploy them to a web server instead of renting a cloud server with computing resources).

Could you please show me how to implement the changes? And after that, is it clear how to deploy it into a web server (like DigitalOcean)? I would be very appreciative if there is some post for similar tasks available online for instructions.

Thanks again, Peter!

**Comment by pjvandehaar** [comment]
Do you have a server that serves static files but won't run python code?

If you rent a DigitalOcean server, it will run the normal python pheweb code just fine.  I think you will have a much better experience maintaining the server and it will work better for your users if you just use the normal python code instead of trying to make static files.

If you really do need a static version of the site, I recommend that you begin by figuring out how to use `wget` (or some other archiving tool) to make the static copy of your site.  After downloading all the html/css/js, you'll be able to see json files that were missed in your browser devtools network tab and can write a script to archive them all.  Once that works, I can help with the searchbox and LocusZoom region-plot movement.

**Comment by stat-yyang** [comment]
Thanks! I misunderstood it previously. Now we decided to use DigitalOcean from your advice. But an unexpected problem comes out: in the pre-installed python 3.6.9, the command `python3 -m install pheweb` failed because of the failure of installing pysam.

I followed your advice here (https://github.com/statgen/pheweb/blob/3530416b3e7975593144b70d7508db3774d783cb/etc/detailed-install-instructions.md#detailed-install-instructions). However, I still cannot solve the problems of installing pheweb. Do you have any suggestions? 

The server is Python/Django Quickstart 1.1 on Ubuntu 18.04. Should I change to another default setting in DigitalOcean or do you have any successful settings to recommend?

**Comment by stat-yyang** [comment]
Uh I solved the installation problem! I simply installed all the packages manually and then installed pheweb successfully.

**Comment by stat-yyang** [comment]
Hi Peter,
I moved all the necessary files to DigitalOcean server (I did not rerun the codes in the server). But encountered another error when serving the website.

======= Exception ====
[Errno 2] No such file or directory: '/root/.pheweb/cache/gene_aliases.marisa_trie'

======= Traceback ====
Traceback (most recent call last):
  File "/root/website/lib/python3.6/site-packages/pheweb/command_line.py", line 148, in main
    run(sys.argv[1:])
  File "/root/website/lib/python3.6/site-packages/pheweb/command_line.py", line 142, in run
    handlers[subcommand](argv[1:])
  File "/root/website/lib/python3.6/site-packages/pheweb/command_line.py", line 70, in serve
    run(argv)
  File "/root/website/lib/python3.6/site-packages/pheweb/serve/run.py", line 132, in run
    from .server import app
  File "/root/website/lib/python3.6/site-packages/pheweb/serve/server.py", line 66, in <module>
    autocompleter = Autocompleter(phenos)
  File "/root/website/lib/python3.6/site-packages/pheweb/serve/autocomplete.py", line 29, in __init__
    self._gene_alias_trie = marisa_trie.BytesTrie().load(common_filepaths['gene-aliases-trie'])
  File "src/marisa_trie.pyx", line 217, in marisa_trie._Trie.load
FileNotFoundError: [Errno 2] No such file or directory: '/root/.pheweb/cache/gene_aliases.marisa_trie'

Do you have any idea what happened?

**Comment by stat-yyang** [comment]
Uh, I corrected the error above. Now our website is launched (http://67.205.180.40:443/). 
Thanks a lot for your help!

Best,
Yue
