### ISSUE TITLE
rsid change or missing

### ISSUE THREAD

**Issue by stat-yyang** [statgen/pheweb#133]
Hi Peter,

we found some interesting things about SNP data in the final displayed results. Many of the SNP data are missing in the generated files. Do you know why this happens?

Thanks a lot!

**Comment by pjvandehaar** [comment]
Nice work getting your site up and running– it looks great and runs fast.

If this is still an issue, could you explain more about it?  Which files are missing which variants, and where had you seen those variants that made you expect them?  Could you copy-paste or screenshot the lines (and headers and a couple lines before/after) for one example of a missing variant?
