### ISSUE TITLE
Can some of the version requirements be updated?

### ISSUE THREAD

**Issue by verdurin** [statgen/pheweb#135]
I'm trying to package `PheWeb` for EasyBuild, for installation on HPC systems (https://easybuild.readthedocs.io/en/latest/).

As such, we build from source and need to specify the versions for individual extensions.

However, I'm seeing something of a clash:

`pheweb 1.1.19 has requirement openpyxl~=2.6, but you have openpyxl 3.0.3.`

The requirement asks for a version of `openpyxl` that can depend on nothing newer than `Python 3.5`. However, I am trying to build for `Python 3.7.4`. Can this requirement be loosened or does the project really depend upon that older `openpyxl`?

I also see this error:

`pheweb 1.1.19 has requirement gunicorn~=19.9, but you have gunicorn 20.0.4.`

Again, I wonder whether this can be updated, though it's less of a roadblock for us than `openpyxl`.

**Comment by pjvandehaar** [comment]
Fixed.  Thanks.  Let me know how it goes.

**Comment by verdurin** [comment]
Yes, that looks to have fixed it, thanks @pjvandehaar 

`gevent` has undergone a pretty radical renumbering of late too, so you might want to update that for your next release.
