### ISSUE TITLE
No plots in variant page

### ISSUE THREAD

**Issue by stat-yyang** [statgen/pheweb#137]
<img width="1440" alt="Screen Shot 2020-07-13 at 8 43 09 AM" src="https://user-images.githubusercontent.com/47928843/87305813-13fb1b80-c4e5-11ea-8847-c491d4c6ccda.png">

Hi,
It seems that there is no plot in the variant page. 
On our website, http://67.205.180.40:443/variant/10:134299394-A-AG  is an example.

Do you know what happened?

Thanks!
Yue

**Comment by Shicheng-Guo** [comment]
Same problem here: "No plots in variant page"

**Comment by pjvandehaar** [comment]
@stat-yyang I can't access that page so I don't know.  Could you send me a screenshot of http://67.205.180.40:443/api/variant/10:134299394-A-AG ?  Could you open devtools' networking tab and check for any errors?  If not, can you make the site reachable for me?

**Comment by stat-yyang** [comment]
> @stat-yyang I can't access that page so I don't know. Could you open devtools' networking tab and console and check for any errors? Can you make the site reachable for me? Could you send me the raw html of that page? Could you send me a screenshot of http://67.205.180.40:443/api/variant/10:134299394-A-AG ?

I am updating the website with some changes. Will notify you as soon as it finishes.

**Comment by stat-yyang** [comment]
> @stat-yyang I can't access that page so I don't know. Could you open devtools' networking tab and console and check for any errors? Can you make the site reachable for me? Could you send me the raw html of that page? Could you send me a screenshot of http://67.205.180.40:443/api/variant/10:134299394-A-AG ?

This is a screenshot of http://67.205.180.40:443/api/variant/10:134299394-A-AG 
<img width="1393" alt="Screen Shot 2020-07-14 at 12 54 07 PM" src="https://user-images.githubusercontent.com/47928843/87453835-25b9ed00-c5d1-11ea-9043-735f8c591d30.png">
The website is still being rebuilt, and now I can serve part of it
<img width="714" alt="Screen Shot 2020-07-14 at 12 54 52 PM" src="https://user-images.githubusercontent.com/47928843/87453899-3cf8da80-c5d1-11ea-8f0c-8303bd9822a7.png">

**Comment by pjvandehaar** [comment]
Can you tell me the version number in `pheweb --help`?  It looks like you're on an older version and there's some bug with the URL used to load the LocusZoom.js javascript library.  Could you update (either via `python3 -m pip install --update pheweb` or `git pull && python3 -m pip install -e .`, depending on how you installed in the first place), and then re-run the `pheweb serve` process?

**Comment by stat-yyang** [comment]
Thanks a lot! 
I upgraded pheweb version to 1.1.21 and now it looks good!

many thanks
