### ISSUE TITLE
Speed up Manhattan Plot

### ISSUE THREAD

**Issue by pjvandehaar** [statgen/pheweb#14]
1. Why do `<script>`s not lookup until 400ms?  What's slowing things down?
2. Why is the XHR starting so much later than the `<script>`s?
3. How long is the d3 taking?  DevTools::Timeline distorts times too much, so use [`console.time('foo'); console.timeEnd('foo');`](https://developer.chrome.com/devtools/docs/console-api#consoletimelabel)

**Comment by sgagliano** [comment]
I don't think the Manhattan Plots are loading slowly. 
Has this issue been resolved?

**Comment by pjvandehaar** [comment]
I'm not sure.  Right now many of the Manhattan Plots have too many points, which is slowing them down.

**Comment by sgagliano** [comment]
@pjvandehaar 

To speed up Manhattan plots: implement Encore's script to only plot the top (1000 or so) variants and then bin the rest

**Comment by sgagliano** [comment]
@pjvandehaar You said that you have fixed this now, right?

**Comment by pjvandehaar** [comment]
Yes.
