### ISSUE TITLE
rsid change or missing

### ISSUE THREAD

**Issue by stat-yyang** [statgen/pheweb#143]
Nice work getting your site up and running– it looks great and runs fast.

If this is still an issue, could you explain more about it?  Which files are missing variants, and where had you seen those variants that made you expect them?  Do you mean that the variants were in your input files but aren't in `generated-by-pheweb/parsed/*.tsv`?  Could you copy-paste or screenshot the lines (and headers and a couple lines before/after) for one example of a missing variant?
_______________________________________________________________________________________________________________________________________
Thanks a lot for your help! I forgot to reply to this issue last month.
For example, in the original input file,
![Screen Shot 2020-08-16 at 11 14 20 AM](https://user-images.githubusercontent.com/47928843/90337654-db51d480-dfb1-11ea-977d-5e3afacd3505.png)
and in *.tsv file,
![Screen Shot 2020-08-16 at 11 03 09 AM](https://user-images.githubusercontent.com/47928843/90337666-ea388700-dfb1-11ea-8a61-e908642e854e.png)
Take a look at the first a couple of lines, they are matched.
There are missing rsid for variants in .tsv file. And some variants have multiple rsid (chrom: 1, pos: 749963)

**Comment by stat-yyang** [comment]
For example, a very famous variant APOE variant rs429358.
It can be searched by the chrom:pos, but can not be searched by its rsid.
http://67.205.180.40:443/variant/19:45411941-C-T
![Screen Shot 2020-09-08 at 10 39 42 AM](https://user-images.githubusercontent.com/47928843/92490934-9c352e80-f1bf-11ea-813d-5505f2dd8593.png)
Is it related to the lookup table we are using? I suppose that some rsids are missing in that lookup table.

**Comment by stat-yyang** [comment]
I found a possible source of the problem.

The unmatched SNPs could be the mismatch of reference and alternate alleles.
For example, 1:693731 G>A can not be matched to rs12238997 because the reference allele in our data is G, not A.

I modified a little bit in add_rsids.py to accommodate the issue.

add 
rsids = rsids + [rsid['rsid'] for rsid in rsid_group if cpra['ref'] == rsid['alt'] and are_match(cpra['alt'], rsid['ref'])]
after line 135

Please correct me if I did something wrong.

**Comment by pjvandehaar** [comment]
PheWeb expects you to have one column of reference alleles, which are exactly what is on the reference genome hg19 or hg38.

For you, is the allele seen on the hg19 reference genome sometimes A1 and sometimes A2?  Or is it always A2?

You can check by running `cat /tmp/v.vcf | tail -n+2 | cut -f1,3,4,5 | detect-ref chr-pos-a1-a2`.  `detect-ref` is included with pheweb, so you probably have it already.  Here's a screenshot of me trying it on some of your data that I typed out:

<img width="762" alt="image" src="https://user-images.githubusercontent.com/862089/105756452-a2336e00-5f1a-11eb-93f2-2b428fed928c.png">
