### ISSUE TITLE
Option request: --njobs for "pheweb process --no-parse"

### ISSUE THREAD

**Issue by Shicheng-Guo** [statgen/pheweb#150]
Hi Peter, 

Do you think we can create an option --njobs which will be quite useful for debug for input files?  For example, the jobs for Manhattan plot is always kills, but it is hard to know which input file has bugs. if we have --njobs 1, we can easily figure out which file should be checked. 

Thanks

Shicheng

**Comment by pjvandehaar** [comment]
Try `pheweb conf num_procs=1 process --no-parse`.
