### ISSUE TITLE
Set PheWeb to use port 8888

### ISSUE THREAD

**Issue by Shicheng-Guo** [statgen/pheweb#151]
Dear Peter, 

I am wondering can I set Pheweb to use port 8888 rather than 5555? 

Another question: I am running pheweb in our HPC (Slurm/Sbatch) and I realize I cannot find where the job is running. For example, I used `top` and `squeue --user myaccount`, neither of them provide me the information where the job is running. 

Thanks.

Shicheng

**Comment by pjvandehaar** [comment]
Run `pheweb serve --port 8888`.

https://slurm.schedmd.com/squeue.html describes how to find which machine is running a job.  `scontrol show job` can do it too.
