### ISSUE TITLE
A pheweb instance needs restarting

### ISSUE THREAD

**Issue by abought** [statgen/pheweb#152]
A user has reported that http://pheweb.sph.umich.edu/FinMetSeq/ instance is not accessible (503 error). See @pjvandehaar  email and slack messages for details.

**Comment by pjvandehaar** [comment]
Done.  Thanks for reporting this.

**Comment by relgamal** [comment]
Hello, it appears this instance needs restarting again. I am getting the following error on the METSIM Pheweb 

"The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later."

Thank you in advance!

**Comment by pjvandehaar** [comment]
What is the URL?

**Comment by relgamal** [comment]
https://pheweb.org/metsim-metab/ Although appears to be working today after ~1 week of being down! Thanks!

**Comment by abought** [comment]
@psnehal was able to restart it earlier today, per Slack internal discussion. I'll mark this issue closed, but feel free to reopen it if you see further issues. Thanks for the bug report: we really appreciate when users give a heads-up about problems. :)

And @pjvandehaar, next time you're in A2, drop me a note!

**Comment by relgamal** [comment]
Thanks @abought ,@psnehal , and @pjvandehaar , appreciate it!
