### ISSUE TITLE
Necessary Data for the Normal Function of Pheweb 

### ISSUE THREAD

**Issue by Shicheng-Guo** [statgen/pheweb#153]
Dear Peter, 

I am wondering is there a list of the necessary files to keep pheweb running. I ask this question because I completed data preparation in HPC and now I need to transfer data to Amazon Cloud where I created a Pheweb frame. Since I think HPC generated lots of non-necessary files (for example, files in tmp folder) which is not necessary for pheweb. Therefore, I am thinking is there a file list to show the necessary files for the normal function of pheweb. 

Thanks. 

Shicheng

**Comment by pjvandehaar** [comment]
See https://github.com/statgen/pheweb/blob/master/etc/detailed-webserver-instructions.md#reducing-storage-use
