### ISSUE TITLE
Remove a phenotype

### ISSUE THREAD

**Issue by jgrundstad** [statgen/pheweb#154]
Is there a way to cleanly remove a problematic phenotype from a completed instance?  I attempted to remove from `pheno-list.json` and ended up getting errors when searching by gene:  

"Error: Sorry, your region requested for phenocode 'bad-pheno' and gene 'GENE1' didn't work.

**Comment by pjvandehaar** [comment]
Option 1: Remove the bad pheno from `pheno-list.json` and then run `pheweb sites -f && pheweb process`.  Parsing won't need to happen again, but everything else will.

Option 2: Remove the bad pheno from `pheno-list.json` and then run `pheweb gather-pvalues-for-each-gene && pheweb top-hits && pheweb phenotypes`.  This leaves the old phenotype littered around various files but unused.  It's what I normally do if I'm in a hurry.

Let me know if this doesn't work for you.
