### ISSUE TITLE
How to host a pheweb accessible on the internet

### ISSUE THREAD

**Issue by Mohammad-Vahed** [statgen/pheweb#161]
Please include:

- the version of pheweb you're using, gotten from `pheweb -h`.  If you're not on the latest version, consider upgrading with `pip3 install --upgrade` and trying again.

Hello.
I several times tried to install the pheweb to the different desktops but every time got the same error,
Could you help me to solve it?
Thank you.

ERROR: Command errored out with exit status 1:
     command: /Library/Developer/CommandLineTools/usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/fs/05kbflqd1xz6pc5fqj7t7z840000gn/T/pip-install-d8_f0gk5/pysam_30e290a207234bf1a494c0a8d71ed110/setup.py'"'"'; __file__='"'"'/private/var/folders/fs/05kbflqd1xz6pc5fqj7t7z840000gn/T/pip-install-d8_f0gk5/pysam_30e290a207234bf1a494c0a8d71ed110/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/fs/05kbflqd1xz6pc5fqj7t7z840000gn/T/pip-record-vtlo95bi/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /Users/mohammad/Library/Python/3.8/include/python3.8/pysam
         cwd: /private/var/folders/fs/05kbflqd1xz6pc5fqj7t7z840000gn/T/pip-install-d8_f0gk5/pysam_30e290a207234bf1a494c0a8d71ed110/
    Complete output (279 lines):
    # pysam: cython is available - using cythonize if necessary
    # pysam: htslib mode is shared
    # pysam: HTSLIB_CONFIGURE_OPTIONS=None
    # pysam: (sysconfig) CC=clang
    # pysam: (sysconfig) CFLAGS=-Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Headers -arch arm64 -arch x86_64
    # pysam: (sysconfig) LDFLAGS=-Wl,-headerpad,0x1000 -arch arm64 -arch x86_64
    checking for gcc... clang
    checking whether the C compiler works... no
    configure: error: in `/private/var/folders/fs/05kbflqd1xz6pc5fqj7t7z840000gn/T/pip-install-d8_f0gk5/pysam_30e290a207234bf1a494c0a8d71ed110/htslib':
    configure: error: C compiler cannot create executables
    See `config.log' for more details
    checking for gcc... clang
    checking whether the C compiler works... no
    configure: error: in `/private/var/folders/fs/05kbflqd1xz6pc5fqj7t7z840000gn/T/pip-install-d8_f0gk5/pysam_30e290a207234bf1a494c0a8d71ed110/htslib':
    configure: error: C compiler cannot create executables
    See `config.log' for more details
    # pysam: htslib configure options: None
    make: ./version.sh: Command not found
    make: ./version.sh: Command not found
    # pysam: htslib_config LIBHTS_OBJS=kfunc.o knetfile.o kstring.o bcf_sr_sort.o bgzf.o errmod.o faidx.o header.o hfile.o hfile_net.o hts.o hts_os.o md5.o multipart.o probaln.o realn.o regidx.o region.o sam.o synced_bcf_reader.o vcf_sweep.o tbx.o textutils.o thread_pool.o vcf.o vcfutils.o cram/cram_codecs.o cram/cram_decode.o cram/cram_encode.o cram/cram_external.o cram/cram_index.o cram/cram_io.o cram/cram_samtools.o cram/cram_stats.o cram/mFILE.o cram/open_trace_file.o cram/pooled_alloc.o cram/rANS_static.o cram/string_alloc.o hfile_libcurl.o
    # pysam: htslib_config LIBS=-lz -lm -lbz2 -llzma -lcurl
    # pysam: htslib_config PLATFORM=Darwin
    # pysam: config_option: ENABLE_GCS=0
    # pysam: config_option: ENABLE_PLUGINS=0
    # pysam: config_option: ENABLE_S3=0
    # pysam: config_option: HAVE_COMMONCRYPTO=0
    # pysam: config_option: HAVE_HMAC=0
    # pysam: config_option: HAVE_LIBBZ2=0
    # pysam: config_option: HAVE_LIBCURL=0
    # pysam: config_option: HAVE_LIBDEFLATE=0
    # pysam: config_option: HAVE_LIBLZMA=0
    # pysam: config_option: HAVE_MMAP=0
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.14.6-x86_64-3.8
    creating build/lib.macosx-10.14.6-x86_64-3.8/pysam
    copying pysam/bcftools.py -> build/lib.macosx-10.14.6-x86_64-3.8/pysam
    copying pysam/config.py -> build/lib.macosx-10.14.6-x86_64-3.8/pysam
    copying pysam/version.py -> build/lib.macosx-10.14.6-x86_64-3.8/pysam
    copying pysam/samtools.py -> build/lib.macosx-10.14.6-x86_64-3.8/pysam
    copying pysam/__init__.py -> build/lib.macosx-10.14.6-x86_64-3.8/pysam
    copying pysam/Pileup.py -> build/lib.macosx-10.14.6-x86_64-3.8/pysam
    copying pysam/utils.py -> build/lib.macosx-10.14.6-x86_64-3.8/pysam
    creating build/lib.macosx-10.14.6-x86_64-3.8/pysam/include
    copying pysam/include/__init__.py -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include
    package init file 'samtools/__init__.py' not found (or not a regular file)
    package init file 'bcftools/__init__.py' not found (or not a regular file)
    package init file 'htslib/__init__.py' not found (or not a regular file)
    package init file 'htslib/htslib/__init__.py' not found (or not a regular file)
    copying pysam/libcsamtools.pxd -> build/lib.macosx-10.14.6-x86_64-3.8/pysam
    copying pysam/libcalignedsegment.pxd -> build/lib.macosx-10.14.6-x86_64-3.8/pysam
    copying pysam/libcbcf.pxd -> build/lib.macosx-10.14.6-x86_64-3.8/pysam
    copying pysam/libctabixproxies.pxd -> build/lib.macosx-10.14.6-x86_64-3.8/pysam
    copying pysam/libcutils.pxd -> build/lib.macosx-10.14.6-x86_64-3.8/pysam
    copying pysam/libchtslib.pxd -> build/lib.macosx-10.14.6-x86_64-3.8/pysam
    copying pysam/libcalignmentfile.pxd -> build/lib.macosx-10.14.6-x86_64-3.8/pysam
    copying pysam/libcvcf.pxd -> build/lib.macosx-10.14.6-x86_64-3.8/pysam
    copying pysam/libctabix.pxd -> build/lib.macosx-10.14.6-x86_64-3.8/pysam
    copying pysam/libcsamfile.pxd -> build/lib.macosx-10.14.6-x86_64-3.8/pysam
    copying pysam/libcbcftools.pxd -> build/lib.macosx-10.14.6-x86_64-3.8/pysam
    copying pysam/libcfaidx.pxd -> build/lib.macosx-10.14.6-x86_64-3.8/pysam
    copying pysam/version.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam
    copying pysam/pysam_stream.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam
    copying pysam/htslib_util.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam
    copying pysam/pysam_util.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam
    copying pysam/csamtools_util.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam
    copying pysam/cbcftools_util.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam
    creating build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/samtools
    copying samtools/sam.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/samtools
    copying samtools/tmp_file.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/samtools
    copying samtools/sam_opts.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/samtools
    copying samtools/bedidx.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/samtools
    copying samtools/bam.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/samtools
    copying samtools/config.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/samtools
    copying samtools/samtools.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/samtools
    copying samtools/bam2bcf.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/samtools
    copying samtools/bam_plbuf.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/samtools
    copying samtools/bam_endian.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/samtools
    copying samtools/stats_isize.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/samtools
    copying samtools/bam_lpileup.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/samtools
    copying samtools/sample.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/samtools
    copying samtools/samtools.pysam.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/samtools
    creating build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/bcftools
    copying bcftools/bam_sample.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/bcftools
    copying bcftools/bcftools.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/bcftools
    copying bcftools/smpl_ilist.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/bcftools
    copying bcftools/vcfbuf.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/bcftools
    copying bcftools/config.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/bcftools
    copying bcftools/prob1.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/bcftools
    copying bcftools/ploidy.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/bcftools
    copying bcftools/vcmp.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/bcftools
    copying bcftools/variantkey.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/bcftools
    copying bcftools/tsv2vcf.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/bcftools
    copying bcftools/call.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/bcftools
    copying bcftools/HMM.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/bcftools
    copying bcftools/bam2bcf.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/bcftools
    copying bcftools/gvcf.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/bcftools
    copying bcftools/regidx.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/bcftools
    copying bcftools/mw.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/bcftools
    copying bcftools/khash_str2str.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/bcftools
    copying bcftools/hex.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/bcftools
    copying bcftools/kmin.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/bcftools
    copying bcftools/rbuf.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/bcftools
    copying bcftools/hclust.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/bcftools
    copying bcftools/kheap.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/bcftools
    copying bcftools/convert.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/bcftools
    copying bcftools/filter.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/bcftools
    copying bcftools/cols.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/bcftools
    copying bcftools/bcftools.pysam.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/bcftools
    copying bcftools/bin.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/bcftools
    creating build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/htslib
    copying htslib/sam_internal.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/htslib
    copying htslib/bcf_sr_sort.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/htslib
    copying htslib/header.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/htslib
    copying htslib/config.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/htslib
    copying htslib/hfile_internal.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/htslib
    copying htslib/hts_internal.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/htslib
    copying htslib/textutils_internal.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/htslib
    copying htslib/thread_pool_internal.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/htslib
    creating build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/htslib/htslib
    copying htslib/htslib/sam.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/htslib/htslib
    copying htslib/htslib/synced_bcf_reader.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/htslib/htslib
    copying htslib/htslib/vcf_sweep.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/htslib/htslib
    copying htslib/htslib/vcf.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/htslib/htslib
    copying htslib/htslib/khash_str2int.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/htslib/htslib
    copying htslib/htslib/bgzf.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/htslib/htslib
    copying htslib/htslib/cram.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/htslib/htslib
    copying htslib/htslib/kstring.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/htslib/htslib
    copying htslib/htslib/knetfile.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/htslib/htslib
    copying htslib/htslib/hts_log.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/htslib/htslib
    copying htslib/htslib/hfile.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/htslib/htslib
    copying htslib/htslib/thread_pool.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/htslib/htslib
    copying htslib/htslib/hts_defs.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/htslib/htslib
    copying htslib/htslib/khash.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/htslib/htslib
    copying htslib/htslib/regidx.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/htslib/htslib
    copying htslib/htslib/faidx.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/htslib/htslib
    copying htslib/htslib/vcfutils.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/htslib/htslib
    copying htslib/htslib/kseq.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/htslib/htslib
    copying htslib/htslib/kfunc.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/htslib/htslib
    copying htslib/htslib/tbx.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/htslib/htslib
    copying htslib/htslib/ksort.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/htslib/htslib
    copying htslib/htslib/kbitset.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/htslib/htslib
    copying htslib/htslib/hts_os.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/htslib/htslib
    copying htslib/htslib/klist.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/htslib/htslib
    copying htslib/htslib/hts.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/htslib/htslib
    copying htslib/htslib/hts_endian.h -> build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/htslib/htslib
    /Users/mohammad/Library/Python/3.8/lib/python/site-packages/setuptools/lib2to3_ex.py:36: SetuptoolsDeprecationWarning: 2to3 support is deprecated. If the project still requires Python 2 support, please migrate to a single-codebase solution or employ an independent conversion process.
      warnings.warn(
    Fixing build/lib.macosx-10.14.6-x86_64-3.8/pysam/bcftools.py build/lib.macosx-10.14.6-x86_64-3.8/pysam/config.py build/lib.macosx-10.14.6-x86_64-3.8/pysam/version.py build/lib.macosx-10.14.6-x86_64-3.8/pysam/samtools.py build/lib.macosx-10.14.6-x86_64-3.8/pysam/__init__.py build/lib.macosx-10.14.6-x86_64-3.8/pysam/Pileup.py build/lib.macosx-10.14.6-x86_64-3.8/pysam/utils.py build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/__init__.py
    Skipping optional fixer: buffer
    Skipping optional fixer: idioms
    Skipping optional fixer: set_literal
    Skipping optional fixer: ws_comma
    Fixing build/lib.macosx-10.14.6-x86_64-3.8/pysam/bcftools.py build/lib.macosx-10.14.6-x86_64-3.8/pysam/config.py build/lib.macosx-10.14.6-x86_64-3.8/pysam/version.py build/lib.macosx-10.14.6-x86_64-3.8/pysam/samtools.py build/lib.macosx-10.14.6-x86_64-3.8/pysam/__init__.py build/lib.macosx-10.14.6-x86_64-3.8/pysam/Pileup.py build/lib.macosx-10.14.6-x86_64-3.8/pysam/utils.py build/lib.macosx-10.14.6-x86_64-3.8/pysam/include/__init__.py
    Skipping optional fixer: buffer
    Skipping optional fixer: idioms
    Skipping optional fixer: set_literal
    Skipping optional fixer: ws_comma
    running build_ext
    skipping 'pysam/libchtslib.c' Cython extension (up-to-date)
    skipping 'pysam/libcsamtools.c' Cython extension (up-to-date)
    skipping 'pysam/libcbcftools.c' Cython extension (up-to-date)
    skipping 'pysam/libcutils.c' Cython extension (up-to-date)
    skipping 'pysam/libcalignmentfile.c' Cython extension (up-to-date)
    skipping 'pysam/libcsamfile.c' Cython extension (up-to-date)
    skipping 'pysam/libcalignedsegment.c' Cython extension (up-to-date)
    skipping 'pysam/libctabix.c' Cython extension (up-to-date)
    skipping 'pysam/libcfaidx.c' Cython extension (up-to-date)
    skipping 'pysam/libcbcf.c' Cython extension (up-to-date)
    skipping 'pysam/libcbgzf.c' Cython extension (up-to-date)
    skipping 'pysam/libctabixproxies.c' Cython extension (up-to-date)
    skipping 'pysam/libcvcf.c' Cython extension (up-to-date)
    building 'pysam.libchtslib' extension
    creating build/temp.macosx-10.14.6-x86_64-3.8
    creating build/temp.macosx-10.14.6-x86_64-3.8/pysam
    creating build/temp.macosx-10.14.6-x86_64-3.8/htslib
    creating build/temp.macosx-10.14.6-x86_64-3.8/htslib/cram
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Headers -arch arm64 -arch x86_64 -I/private/var/folders/fs/05kbflqd1xz6pc5fqj7t7z840000gn/T/pip-install-d8_f0gk5/pysam_30e290a207234bf1a494c0a8d71ed110/htslib -I/private/var/folders/fs/05kbflqd1xz6pc5fqj7t7z840000gn/T/pip-install-d8_f0gk5/pysam_30e290a207234bf1a494c0a8d71ed110/samtools -I/private/var/folders/fs/05kbflqd1xz6pc5fqj7t7z840000gn/T/pip-install-d8_f0gk5/pysam_30e290a207234bf1a494c0a8d71ed110/samtools/lz4 -I/private/var/folders/fs/05kbflqd1xz6pc5fqj7t7z840000gn/T/pip-install-d8_f0gk5/pysam_30e290a207234bf1a494c0a8d71ed110/bcftools -I/private/var/folders/fs/05kbflqd1xz6pc5fqj7t7z840000gn/T/pip-install-d8_f0gk5/pysam_30e290a207234bf1a494c0a8d71ed110/pysam -I/private/var/folders/fs/05kbflqd1xz6pc5fqj7t7z840000gn/T/pip-install-d8_f0gk5/pysam_30e290a207234bf1a494c0a8d71ed110 -I/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8 -c pysam/libchtslib.c -o build/temp.macosx-10.14.6-x86_64-3.8/pysam/libchtslib.o -Wno-unused -Wno-strict-prototypes -Wno-sign-compare -Wno-error=declaration-after-statement
    In file included from pysam/libchtslib.c:4:
    In file included from /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8/Python.h:11:
    In file included from /Library/Developer/CommandLineTools/usr/lib/clang/12.0.0/include/limits.h:21:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/limits.h:63:
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/cdefs.h:807:2: error: Unsupported architecture
    #error Unsupported architecture
     ^
    In file included from pysam/libchtslib.c:4:
    In file included from /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8/Python.h:11:
    In file included from /Library/Developer/CommandLineTools/usr/lib/clang/12.0.0/include/limits.h:21:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/limits.h:64:
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/machine/limits.h:8:2: error: architecture not supported
    #error architecture not supported
     ^
    In file included from pysam/libchtslib.c:4:
    In file included from /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8/Python.h:25:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdio.h:64:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:71:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_types.h:27:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:33:
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/machine/_types.h:34:2: error: architecture not supported
    #error architecture not supported
     ^
    In file included from pysam/libchtslib.c:4:
    In file included from /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8/Python.h:25:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdio.h:64:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:71:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_types.h:27:
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:55:9: error: unknown type name '__int64_t'
    typedef __int64_t       __darwin_blkcnt_t;      /* total blocks */
            ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:56:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
    typedef __int32_t       __darwin_blksize_t;     /* preferred block size */
            ^
    note: '__int128_t' declared here
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:57:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
    typedef __int32_t       __darwin_dev_t;         /* dev_t */
            ^
    note: '__int128_t' declared here
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:60:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
    typedef __uint32_t      __darwin_gid_t;         /* [???] process and group IDs */
            ^
    note: '__uint128_t' declared here
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:61:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
    typedef __uint32_t      __darwin_id_t;          /* [XSI] pid_t, uid_t, or gid_t*/
            ^
    note: '__uint128_t' declared here
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:62:9: error: unknown type name '__uint64_t'
    typedef __uint64_t      __darwin_ino64_t;       /* [???] Used for 64 bit inodes */
            ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:68:9: error: unknown type name '__darwin_natural_t'
    typedef __darwin_natural_t __darwin_mach_port_name_t; /* Used by mach */
            ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:70:9: error: unknown type name '__uint16_t'; did you mean '__uint128_t'?
    typedef __uint16_t      __darwin_mode_t;        /* [???] Some file attributes */
            ^
    note: '__uint128_t' declared here
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:71:9: error: unknown type name '__int64_t'
    typedef __int64_t       __darwin_off_t;         /* [???] Used for file sizes */
            ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:72:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
    typedef __int32_t       __darwin_pid_t;         /* [???] process and group IDs */
            ^
    note: '__int128_t' declared here
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:73:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
    typedef __uint32_t      __darwin_sigset_t;      /* [???] signal set */
            ^
    note: '__uint128_t' declared here
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:74:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
    typedef __int32_t       __darwin_suseconds_t;   /* [???] microseconds */
            ^
    note: '__int128_t' declared here
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:75:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
    typedef __uint32_t      __darwin_uid_t;         /* [???] user IDs */
            ^
    note: '__uint128_t' declared here
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:76:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
    typedef __uint32_t      __darwin_useconds_t;    /* [???] microseconds */
            ^
    note: '__uint128_t' declared here
    In file included from pysam/libchtslib.c:4:
    In file included from /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8/Python.h:25:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdio.h:64:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:71:
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_types.h:43:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
    typedef __uint32_t      __darwin_wctype_t;
            ^
    note: '__uint128_t' declared here
    In file included from pysam/libchtslib.c:4:
    In file included from /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8/Python.h:25:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdio.h:64:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:75:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types/_va_list.h:31:
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/machine/types.h:37:2: error: architecture not supported
    #error architecture not supported
     ^
    fatal error: too many errors emitted, stopping now [-ferror-limit=]
    20 errors generated.
    error: command 'clang' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Library/Developer/CommandLineTools/usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/fs/05kbflqd1xz6pc5fqj7t7z840000gn/T/pip-install-d8_f0gk5/pysam_30e290a207234bf1a494c0a8d71ed110/setup.py'"'"'; __file__='"'"'/private/var/folders/fs/05kbflqd1xz6pc5fqj7t7z840000gn/T/pip-install-d8_f0gk5/pysam_30e290a207234bf1a494c0a8d71ed110/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/fs/05kbflqd1xz6pc5fqj7t7z840000gn/T/pip-record-vtlo95bi/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /Users/mohammad/Library/Python/3.8/include/python3.8/pysam Check the logs for full command output.

**Comment by pjvandehaar** [comment]
What command did you run to try to install pheweb?

**Comment by Mohammad-Vahed** [comment]
Hi Peter,

I followed your instructions:
>>
python3 -m pip install -U cython wheel pip setuptools
python3 -m pip install pheweb
pheweb --help
(Note: In most cases this is equivalent to pip3 install pheweb, but if you have a bad version of pip3 on your $PATH, using python3 -m pip will avoid it.)

If you get the error Segmentation fault (core dumped), try running python3 -m pip install --no-binary=cffi,cryptography,pyopenssl pheweb instead. (more info)

If you get an error related to pysam, run python3 -m pip install -U cython; python3 -m pip install https://github.com/pysam-developers/pysam/archive/master.zip and try again.
>>

And I tested into two different Mac systems, both had the same error!

**Comment by pjvandehaar** [comment]
Do you have XCode developer tools installed?  Try `sudo xcode-select --install`.

If you scroll down a bit on that page you'll see instructions for installing with miniconda3, and those should work for you.

**Comment by Mohammad-Vahed** [comment]
Hi,

Thanks a lot for your contributions to the Pheweb project. It's amazing to see the results displayed on a website.
I am quite new to web development. I am exploring deploying the website built locally to the public.
Now I have followed all the steps in your instructions and served the Pheweb and I can access it using my own computer (PC). However, I would like to make it public and allow everyone to access it.
Could you guide me on how I can deploy Pheweb App?
What are you recommend to the best way to publish/deploy the Pheweb App?

Thanks!

**Comment by pjvandehaar** [comment]
Great, I’m glad it works for you!

What command are you using to serve the pheweb on your computer?      

The README has instructions for running a pheweb on a server accessible to the internet. They’re not great and I’ll improve them sometime, so thanks for reminding me of them.

**Comment by Mohammad-Vahed** [comment]
Hi,

Thank you, I used "pheweb serve --open" to open "localhost:5000" (on Ubuntu). I would people can access Pheweb by specific domain or IP. (for the first test on our samples)
Before using the AWS, we rather test in a PC as a server and get results and show them on the website.
I always deploy web tools by VS, but for an installed App and using the command for a run ""pheweb serve --open""  I do know!!! 
Please guide me.

I appreciate you.

**Comment by pjvandehaar** [comment]
What's VS?

**Comment by Mohammad-Vahed** [comment]
Hi,
Sorry, I mean how can set up Pheweb to access in public domain? for example as your web site: https://pheweb.org/UKB-TOPMed/
Or: http://67.205.180.40:443/

**Comment by pjvandehaar** [comment]
I don't understand what you're having trouble with.  You need a computer with a stable IP address that can be reached from the internet.  ie, a server.  It sounds like you don't have one, so you'll need to ask a sysadmin where you work/study or rent a VPS.  

It's probably easier to experiment using `python3 -m http.server 5000` or something like that instead of pheweb.

If you want to rent a VPS, you can follow this tutorial: https://www.digitalocean.com/community/tutorials/how-to-set-up-an-ubuntu-20-04-server-on-a-digitalocean-droplet .
