### ISSUE TITLE
config.py template, and host on dreamhost.com

### ISSUE THREAD

**Issue by jielab** [statgen/pheweb#168]
Hi, there:

The installation guide for pheweb is TOO simple. There is nothing for me to "git clone"? I only need to run "pip3 install pheweb" and then create a directory and write a config.py file and throw a GWAS file there, and then everything will run magically?
Is there a template config.py file that I could use?

Also, I have been using dreamhost.com for unlimited hosting. Is there a guide on how to run pheweb from 3rd servers such as dreamhost.com? I think I would not be able to run "pheweb serve --open" from such a 3rd party server. I would deeply appreciate if someone coudl share some experience on this.

Thank you & best regards,
Jie

**Comment by pjvandehaar** [comment]
You’re right, that’s a great point.

1. I think I’ll add a command `pheweb init` which makes `config.py` with
some comments about settings you might want. What do you think?

2. Maybe I’ll add a sample directory to the repo that’s easy to run.
There’s already something like that in the test directory but would it be
helpful if I had a simple folder with a `config.py` and input data and a
simple shell script to run everything?

3. The README has instructions for how to serve pheweb from a VPS like
Dreamhost here:
https://github.com/statgen/pheweb#6-serve-the-website

**Comment by pjvandehaar** [comment]
I'm at a computer now and re-reading your post.  What is it specifically that you're unsure of with Dreamhost?  I wrote the instructions at https://github.com/statgen/pheweb/blob/master/etc/detailed-webserver-instructions.md#hosting-a-pheweb-and-accessing-it-from-your-browser to help people in your situation, but it's hard to be comprehensive and I probably missed some important parts.  Hopefully those instructions will get you connected to your pheweb using an IP address.  If you want a domain name instead, that won't require any changes to your server, but I can help with that when you reach that point.

**Comment by jielab** [comment]
Dear Peter:

Thank you very much! It would be really helpful if I could use something like "git clone pheweb" to get all necessary files including config.py and an example.sh script to run an example.

I think this is quite standard for the Github community.

Best regards,
Jie

**Comment by jielab** [comment]
Dear Peter:

I now created the confiy.py and two testing GWAS. However, please see the screenshot below, there is error.

Can you please let me know what is happening and how to fix this?

Best regadrs,
Jie

![11](https://user-images.githubusercontent.com/26947455/129491694-66834a68-b2b9-4287-a396-fe898b064f0b.png)

**Comment by pjvandehaar** [comment]
What’s in “parse-failures.txt”?

2. Pheweb needs columns “chrom” and “pos”

**Comment by jielab** [comment]
Dear Peter:

My GWAS file has CHR and POS. I just checked the error message and found that it is due to some POS is not sorted. I fixed it and now it works.

Please see the screenshot below. After I typed "pheweb process", my screen shows "Completed", and then the terminal stays idle. Am I supposed to wait for something to happen?  I waited for a few minutes, nothing happened. Then I killed it, and run the next command "pheweb serve --open" but it says  "*-sqlite3 was requested but does not exist". Is this because the previous command "pheweb process" did not finish?

Best regards,
Jie

![屏幕截图 2021-08-16 160019](https://user-images.githubusercontent.com/26947455/129531577-702bf982-3293-47c5-834c-c35df5228d78.png)

**Comment by pjvandehaar** [comment]
Great, I'm glad this worked!
