### ISSUE TITLE
"pip3 install pheweb" failed

### ISSUE THREAD

**Issue by jielab** [statgen/pheweb#169]
Dear Peter:

Please see the error message below. I tried to run "pip3 install pheweb" on a remote server, which has python2 as default (it does have python3 installed).

![111](https://user-images.githubusercontent.com/26947455/129492777-332ca267-194d-4923-9db8-a81b864293f7.png)

Can you please let me know how to address this issue?

Thank you & best regards,
Jie

**Comment by hyunminkang** [comment]
If you use conda to make python3 as default, wouldn't it solve the problem?

Hyun.

**Comment by pjvandehaar** [comment]
I think your screenshot missed part of the error on the right side.

**Comment by jielab** [comment]
Dear Hyun:

I now used "alias" to make python3 as the default. However, the error message still persists, shown as below.
![11](https://user-images.githubusercontent.com/26947455/129926279-7d24a7fd-249d-4e39-bb45-6355079d8634.png)

Can you please let me know what is the cause of this error?

You said to "use conda to make python3 as default". Exactly how to do that? I thought that "conda" is not involved. We simply used "pip3 install pheweb". 

Best regards,
Jie

**Comment by pjvandehaar** [comment]
1. What kind of machine are you running on?

2. Please show results of `lsb -a` and `uname -a`

3. Please show results of `ls -l /tmp/pip-build-wf4.../...linux-gnu.so` (with the filepath in your screenshot).  `ls -l` should that it is executable.  See <https://stackoverflow.com/questions/62766758/how-to-fix-python-error-failed-to-map-segment-from-shared-object-appearing>.

If this doesn't work, just install miniconda and use that.

**Comment by jielab** [comment]
Dear Peter:

Below is the log, based on your instruction

![image](https://user-images.githubusercontent.com/26947455/129951694-20583909-df3a-47c0-82e5-19d00ab2a395.png)


Best regards,
Jie

**Comment by pjvandehaar** [comment]
That wasn’t quite what I intended.  We could figure this out but it might take more time than either of us wants to spend.  You mentioned that you work with a programmer— maybe they should read this issue and try?
