### ISSUE TITLE
Show GWAS Catalog info on [LZ, PheWAS]

### ISSUE THREAD

**Issue by pjvandehaar** [statgen/pheweb#17]
### The GWAS Catalog

The [GWAS Catalog](https://www.ebi.ac.uk/gwas/docs/downloads) has 25k entries.
Each entry has:
- a study name (eg, "Newly identified genetic risk variants for celiac disease related to the immune response.")
- one of 1400 "Disease/Trait" labels (eg, "Type 2 diabetes", "Systemic lupus erythematosus")
- a link to an abstract (eg http://www.ncbi.nlm.nih.gov/pubmed/18204446).
### Approaches to selecting GWAS Catalog entries for each phewas code:
1. For each phewas code, manually search for matching GWAS Catalog label.
   - I would need help with this, because I need to understand the diseases.
2. Then search for matching study names that were missed.

Is it worth automating?  Let's do some by hand and then decide.
### Goncalo's Approach for BDSI
1. Filter to rs#s that match nicely between MGI and GWAS Catalog (MAF, etc).
2. For each phewas_code, find the GWAS Catalog trait that makes our data most likely:

`product_{each row}(P(OR_{obs} | OR_{GWAS}, SE)) / the null`

**Comment by pjvandehaar** [comment]
Simple solution:

**Comment by abecasis** [comment]
I think there might be too many to highlight in Manhattans... might get better mileage highlighting them on LocusZoom plots.

G

**Comment by pjvandehaar** [comment]
Without any attempt to connect the 1400 GWAS Catalog traits to pheweb traits:

- on LZ: highlight all GWAS Catalog variants (toggleable?)
- on a variant (PheWAS) page: mention if a variant is in the GWAS Catalog
    - and also if it's within 10kb of one?  or perhaps LD > 0.2?
- on Manhattan plots: allow the user to search for GWAS Catalog traits to show.
    - we could try to remember & suggest the traits people search for, but that's likely as much work as simple statistics comparing GWASCatalog traits to PheWeb traits.

**Comment by pjvandehaar** [comment]
This could maybe live in the portal's API.

**Comment by sgagliano** [comment]
GWAS Catalog has been incorporated into LZ plots.
