### ISSUE TITLE
host Pheweb on Dreamhost.com

### ISSUE THREAD

**Issue by jielab** [statgen/pheweb#171]
Hi, there:

If someone had successfully installed and hosted pheweb on a commercial server such as Dreamhost.com, can you please kindly share how to do it. I am a paid customer of Dreamhost with a "unlimited host" plan.

Best regards,
Jie

**Comment by pjvandehaar** [comment]
You should either just try it, or ask Dreamhost support for information about running a Flask python app.  This isn't a pheweb issue, so I'm closing it.
