### ISSUE TITLE
other allowed column names	

### ISSUE THREAD

**Issue by Shicheng-Guo** [statgen/pheweb#172]
LOG10P: I already have -LOG10P in my summary statistics. Do you think we can make the system compatible to LOG10P ? 

(summary statistics are from REGENIE 2.2.4)

Thanks
Shicheng

**Comment by pjvandehaar** [comment]
Yeah, the branch https://github.com/statgen/pheweb/tree/neglog10 tries to switch over from storing pvalue to neglog10pvalue but I haven’t finished it yet. Is that something you’re interested in helping with?
