### ISSUE TITLE
one line fix for add_rsids.py

### ISSUE THREAD

**Issue by jielab** [statgen/pheweb#173]
Dear Peter and guys:

Previously I mentioend that it is a pity (not necessarily a bug) that Pheweb could not find rsIDs for SNPs simply because their A1/A2 alleles are not the same as the REF/ALT allele. I said that this idea of a single REF/ALT allele in the "reference genome" will be abandoned, because now there are more and more genomes in the reference.

I just took a look at your add_rsids.py code. Even though I had no experience in python programming, I believe that only one line will fix this issue. As shown in the following screenshot, I think we simply need to add **or (cpra['ref'] == rsid['alt'] and are_match(cpra['alt'], rsid['ref']))** to the end of line 140. 

![image](https://user-images.githubusercontent.com/26947455/131502476-5ea31a54-3ba6-4424-9cfe-60c3c297a3fc.png)

I feel that updating this line is really important. Also, it would be good to be case insensitive, so that **a/c is equal to A/C**. 

Best regards,
Jie

**Comment by pjvandehaar** [comment]
It sounds like this change will work for you, but I don't want it in pheweb, sorry.  I like ref/alt.
