### ISSUE TITLE
best practice for adding new summary statistics files

### ISSUE THREAD

**Issue by Shicheng-Guo** [statgen/pheweb#174]
I have deposited about 2000 phenotypes into my personal pheweb server few month ago. However, now I need to deposit another 200 summary statistics files. Is there any suggestion how to do this task with high efficiency. 

Thanks
Shicheng

**Comment by pjvandehaar** [comment]
No, sorry.  Just update `pheno-list.json` and re-run `pheweb process` and it'll regenerate what you need.

If you want to leave the original site running while you load the new one, you can copy it with hardlinks using `cp -l -r`.  I don't think that anything in pheweb overwrites files in-place, but if it does then that will cause problems.

The parsing (`pheweb parse` which populates `generated-by-pheweb/parsed/*`) won't need to happen again, but everything else will.

PheWeb could have been written to make adding phenotypes fast, but it wasn't.  It would need (1) a fast rsid annotator using <2GB RAM and (2) a way to update the big pheno-vs-variant matrix that's used for single-variant PheWAS lookups.

**Comment by Shicheng-Guo** [comment]
Clear!! Thanks @pjvandehaar
