### ISSUE TITLE
failed to run 'pip3 install pheweb'

### ISSUE THREAD

**Issue by christine1729** [statgen/pheweb#179]
- the command you were running and its output/error.

<img width="1197" alt="Screen Shot 2021-09-07 at 17 57 52" src="https://user-images.githubusercontent.com/38834129/132428634-b513ab2c-26e2-4e74-8443-6fb82697a952.png">

Hi Peter, I've tried multiple ways but still failed to install. Is there anyway to resolve it? 

Thanks a lot,
christine1729

**Comment by pjvandehaar** [comment]
Was there more to the error message?  Could you post that?

**Comment by christine1729** [comment]
Hi @pjvandehaar,

Thanks a lot for your reply. Yep I've tried miniconda but still got error.

Error below:
![Screen Shot 2021-09-07 at 21 14 09](https://user-images.githubusercontent.com/38834129/132445515-3798e57e-d227-464f-aca1-3953223b61e9.png)
![Screen Shot 2021-09-07 at 21 14 34](https://user-images.githubusercontent.com/38834129/132445560-df8714b6-ded4-498c-b0f3-e29f00819498.png)
![Screen Shot 2021-09-07 at 21 14 57](https://user-images.githubusercontent.com/38834129/132445590-05eb9112-f730-4d90-b756-169a0a9a6789.png)
![Screen Shot 2021-09-07 at 21 15 11](https://user-images.githubusercontent.com/38834129/132445610-1a8c77fd-28f4-43dd-9644-7d0d4a0d0cce.png)

**Comment by pjvandehaar** [comment]
Huh.  I don't understand what's wrong with `blist`. The error with `pysam` confuses me: "C compiler cannot create executables".  Do you get the same two errors with miniconda?

I recommend that you:

(a) google those errors and try whatever people recommend, or

(b) install homebrew and try `brew install python3; python3 -m pip install pheweb`.

**Comment by pjvandehaar** [comment]
PheWeb no longer uses `blist`.
