### ISSUE TITLE
Save manhattan plot as png/svg

### ISSUE THREAD

**Issue by 11Dmitriy11** [statgen/pheweb#198]
Hello!
Is there a way to save manhattan plots as png/svg or pdf file?
For PheWAS there is a botton for saving, but for GWAS not. It's probably easier to make such a picture in python than to add a save button. How can I make this graph in python or add button to save from website?

Thank you!

**Comment by pjvandehaar** [comment]
I expect that you can just take a screenshot.  If you find or build a
better solution, let me know, and we can merge it.
