### ISSUE TITLE
URI as assoc_files in pheno_list.json

### ISSUE THREAD

**Issue by vineetver** [statgen/pheweb#205]
Please include:

- Version: pheweb 1.1

- pheweb parse-input-files.

- Error: Cannot make /Users/viv064/PycharmProjects/pheweb2/pheweb/generated-by-pheweb/parsed/008.5 because https://*.s3.amazonaws.com/UKB_GATE/sumstats/pheno.008.5.GATE.txt.vcf.gz does not exist even tho this file exists

Clearly, pheweb does not expect a URI as a file path. Is there any workaround for this? 

Thank you for your help.

**Comment by pjvandehaar** [comment]
The easiest way would be to use s3fuse on your machine.
