### ISSUE TITLE
ModuleNotFoundError: No module named 'pheweb.command_line'

### ISSUE THREAD

**Issue by sylee20** [statgen/pheweb#211]
I first tried to install with `'pip3 install pheweb'` but got `'permission denied'` error. 

So I installed with the code suggested in 'detailed install instructions'.
```
sudo apt-get update
sudo apt-get install python3-pip python3-dev libz-dev libffi-dev
sudo python3 -m pip install wheel cython
sudo python3 -m pip install pheweb
```
Then I wanted to check if it's properly installed by typing `'pheweb --help'`
but I got this error:
```
Traceback (most recent call last):
  File "/usr/local/bin/pheweb", line 5, in <module>
    from pheweb.command_line import main
ModuleNotFoundError: No module named 'pheweb.command_line'
```

**This is what else I've tried:**

1. I ran this code:
```
echo 'PATH="$HOME/.local/bin:$PATH"' >> ~/.bashrc
```
Then closed the session and opened a new one but got the same error 

2. When I run this code:
```
sudo python3 -m pip show pheweb
```
I get this result:
```
Name: PheWeb
Version: 1.3.16
Summary: A tool for building PheWAS websites from association files
Home-page: <https://github.com/statgen/pheweb>
Author: Peter VandeHaar
Author-email: pjvh@umich.edu
License: UNKNOWN
Location: /usr/local/lib/python3.6/dist-packages
Requires: boltons, cffi, Flask, Flask-Compress, Flask-Login, gevent, gunicorn, intervaltree, numpy, psutil, pysam, rauth, requests, scipy, tqdm, wget
```

I tried adding this to  /.bashrc file but it didn't workout:
```
PATH="/usr/local/lib/python3.6/dist-packages:$PATH"
```

3. I uninstalled and re-installed pheweb but still got the same error.

Can you please help me address this issue?

Thank you.

**Comment by pjvandehaar** [comment]
What if you run “sudo pheweb”?

If that doesn’t work, I recommend installing miniconda3 and using that to
install pheweb.

**Comment by sylee20** [comment]
Running "sudo pheweb" solved the problem.
Thank you so much for your help!

**Comment by pjvandehaar** [comment]
Thanks for letting me know that it worked.  I updated the instructions.
