### ISSUE TITLE
pheweb to display multiple GWAS?

### ISSUE THREAD

**Issue by jielab** [statgen/pheweb#216]
Hi, guys:

I am wondering if pheweb could display multiple GWAS into a consolidated Manhattan plot, something like this **_topr_** (https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-023-05301-4/figures/1). As you see from the right side of this Figure generated by topr, it plots 4 GWAS in the same place: 3 individual GWAS above the X-axis, 1 meta-analysis GWAS below the X-axis.

Usually, when we here **phe**-something, we expect that we could display multiple phenotypes at the same place. The above mentioned **_topr_** could also generate locuszoom plot. Since locuszoom is a brand tool from you guys, it would be great to incorporate.

Best regards,
Jie

**Comment by pjvandehaar** [comment]
If can't.  If you send a PR and the code is good I'll merge it.
