### ISSUE TITLE
Allow searching by gene

### ISSUE THREAD

**Issue by sgagliano** [statgen/pheweb#22]

**Comment by pjvandehaar** [comment]
- [ ] make a json file like:

    ```
    {
      "TNFSF13B": {
        "aliases": ["BAFF"],
        "chrom": "13",
        "pos_start": 108903588,
        "pos_end": 108960832,
        "phenocodes": ["527.11", "321.11", ... ]
      }, 
      ...
    }
    ```

    The list `phenocodes` will contain the phenotype with the smallest pval in that gene, and continue on with more until pval rises above 1e-6.  If no traits have variants in this gene, it will be empty.  (In that case, it will return the url `/error?message=sorry, no phenotypes have variants in the region 1:23,334-343,234`)

- [ ] Make a trie mapping autocompletable gene names to their canonical name.  I don't know how to handle genes with multiple definitions but I don't care much so it's okay.  Make `autocomplete.py` use this trie.  It will return the URL of the best phenotype.

- [ ]

**Comment by pjvandehaar** [comment]
When a user searches for a gene, what region should be shown?  Just the gene plus `max(200bp, 5%)` up and downstream?  Sarah says that the ideal region varies by gene.  If there's a peak near a gene, it might be good to extend the gene's region to capture that peak.

**Comment by pjvandehaar** [comment]
### Getting gene aliases

dnSNFP gets their gene aliases from http://www.genenames.org/ .  I want the columns [`symbol`, `prev_symbol`, `alias_symbol`].  I might also want `ensembl_gene_id`.

The full dataset (in json) is at:
- <ftp://ftp.ebi.ac.uk/pub/databases/genenames/new/json/non_alt_loci_set.json>
- <ftp://ftp.ebi.ac.uk/pub/databases/genenames/new/tsv/non_alt_loci_set.txt>

From the page <http://www.genenames.org/cgi-bin/statistics> I can select many which type of gene I want.  TODO: figure out which of those files (or maybe a few of them) I need.  I can also build a custom download with only the columns I need.

**Comment by pjvandehaar** [comment]
### Files I need:

- For annotating variants, I need a file that can be loaded into `BisectFinder`, meaning that it contains [`DISPLAYNAME`, `chr`, `start`, `end`].
- For `/region/<phenocode>/gene/<DISPLAYNAME>`, I need a map `DISPLAYNAME` -> (`chr`, `start`, `end`).
- For `/gene/<DISPLAYNAME>`, I need a map `DISPLAYNAME` -> (`chr`, `start`, `end`, [`significant_phenocode`, ...])
- For autocomplete, I need a trie that maps `SYNONYM` -> [`DISPLAYNAME`, ...].  If it links to one, success.  If multiple, error.

**Comment by pjvandehaar** [comment]
### Number of phenotypes to show

Matthew recommends showing 2-9 phenotypes, depending on their significance level, and showing the p-values beside them (perhaps with a sparkline).
