### ISSUE TITLE
pheweb-rg-pipeline does NOT work

### ISSUE THREAD

**Issue by jielab** [statgen/pheweb#220]
Hi, there:

Previously I reported that I could NOT make [**pheweb-rg-pipeline**](https://github.com/statgen/pheweb-rg-pipeline) work. 
Basically, **conda install LDSC** runs under **python2**. I could install nextflow through **conda install nextflow** but it will NOT run after I execute **conda activate LDSC**.  So, can you please give a step-by-step and correct tutorial on how to install pheweb-rg-pipeline. 

The  Github page for pheweb-rg-pipeline said "inside the LDSC/nextflow.config file". But where is that file? As I said, I installed LDSC through **conda install LDSC**. Should I also **git clone** the LDSC repository?  

Finally, I decided to run LDSC locally and separately, and I generated an output file like below:
![image](https://github.com/statgen/pheweb/assets/26947455/015604b8-9f51-45e3-af79-b1c0113113ff)

However, after I put this file into the same folder as pheweb, I got the following **error**:
![image](https://github.com/statgen/pheweb/assets/26947455/d93ad4a3-d206-47af-87f3-aa1c0b5e1927)

Can someone please help out here? 
I would hate to see that I could not make the amazing pheweb-rg-pipeline work.

Thank you & best regards,
Jie

**Comment by sgagliano** [comment]
Hi Jie, 

Information on how to run the pheweb-rg pipeline is outlined in the README of the following GitHub repository: https://github.com/statgen/pheweb-rg-pipeline/tree/master. 
The file you are referring to (nextflow.config) is found in this repository, specifically here: https://github.com/statgen/pheweb-rg-pipeline/blob/master/LDSC/nextflow.config. 

As a side note, based on the naming of your correlations file, it seems that you are testing the same trait (height) across different genetic ancestries. As noted in the pheweb-rg pipeline README, it is currently set-up to run on summary statistics derived from individuals of European genetic ancestry  (i.e. the pipeline is using LDSC-supplied LD scores based off of LD patterns in the 1000 Genomes European super-population). I would suggest exploring other summary statistics-based tools for estimating genetic correlation assuming a diverse set of samples. 

Hope this helps.
