### ISSUE TITLE
METSIM Pheweb Instance Not Working

### ISSUE THREAD

**Issue by relgamal** [statgen/pheweb#222]
Hello, it appears this instance needs restarting again. I am getting the following error on the METSIM Pheweb 

"The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later."

Thank you in advance!

_Originally posted by @relgamal in https://github.com/statgen/pheweb/issues/152#issuecomment-2054442291_

**Comment by abought** [comment]
Snehal was able to restart it earlier today, per Slack internal discussion. I'll mark this issue closed, but feel free to reopen it if you see further issues. Thanks for the bug report: we really appreciate when users give a heads-up about problems. :)
