### ISSUE TITLE
the content of pheweb

### ISSUE THREAD

**Issue by dqq0404** [statgen/pheweb#223]
Hi,
This question may be simple, but I still want to ask it. Does the pheweb  include the recently released sumstats data of OCT phenotypes and the previous sumstats data of brain phenotypes? Because I searched for related phenotypes, but I didn’t find it.

**Comment by sgagliano** [comment]
Hello. Thank you for your question. The UK Biobank instances of PheWeb (e.g. TOPMed-imputed UK Biobank: https://pheweb.org/UKB-TOPMed/) only displays ICD code-based PheCodes. Hope this helps.
