### ISSUE TITLE
Not clear when 3 parts of pheweb (executable, python scripts, huge dbSNP files) got installed

### ISSUE THREAD

**Issue by jielab** [statgen/pheweb#224]
Hi, guys:

It is really impressive that pheweb could got installed easily, basically first **pip3 install pheweb** and then **pheweb process**.  Of course, before **pheweb process**, users need to create a pheno list file and a configuration file. 

I can understand that **pip3 install pheweb** will generate a **pheweb executable** into /home/ME/.local/bin/ directory. 

My question is: **when and how and where the actual python scripts are installed?** I don't know where to locate them.  The pheweb executable only has 6 lines of code. Does it call some actual python scripts?

Similarly: **when and how the huge dbsnp files got downloaded?** I don't want pheweb to download them repeatedly since I already have a copy of these files on my computer.

Your explanation would be greatly appreciated.

Thank you & best regards,
jie

**Comment by pjvandehaar** [comment]
https://stackoverflow.com/questions/58159607/is-it-possible-and-how-to-see-the-python-source-code-for-the-package-that-is-i

I don't remember about dbsnp. I think there's an option you can set to use a cache directory.
