### ISSUE TITLE
Starting `pheweb add-rsids`, Completed in 57 minutes

### ISSUE THREAD

**Issue by jielab** [statgen/pheweb#226]
Hi, there:

I am using PheWeb version 1.3.16. 

My config.py file is as below:
```
hg_build_number = 19
assoc_max_maf = 1
show_correlations = False
show_manhattan_filter_button = True
cache = "/mnt/d/data/dbsnp/"
field_aliases = {'CHR':'chrom'
```

My pheweb command works fine. 
However, as I wrote in the title, it took 57 minutes to add-rsids for only 2 GWAS. My GWAS file already have rsIDs in the "SNP" column.

How could I tell pheweb NOT to add-rsids since my GWAS already have them?

Best regards,
Jie

**Comment by pjvandehaar** [comment]
There's not a way to do that.  It would require changing ~5 lines of code.

**Comment by jielab** [comment]
I will shut up, from now on. Wish your amazing software is enjoyed by a lot users.
