### ISSUE TITLE
interpretation

### ISSUE THREAD

**Issue by Afreen89** [statgen/pheweb#227]
Hello, 

The sumstats I have has effect allele and other allele, could you specify if you are taking reference as effect allele or the other allele in the code here:

![image](https://github.com/statgen/pheweb/assets/101992840/004f76db-a011-4fc9-8c23-7548b7ea2a9c)

I am new in the field, its confusing for me between effect allele, reference allele, major allele and A1. I am giving it a sumstats for a few phenotypes, and I have effect and other allele. I am just renaming the columns to match the code.

**Comment by sgagliano** [comment]
Hello. Thanks for the question. The alternate allele, A2 (i.e.non-reference allele) is the effect allele.

Hope this helps!
