### ISSUE TITLE
QQ CI

### ISSUE THREAD

**Issue by sgagliano** [statgen/pheweb#23]
@pjvandehaar 

- In SardiNIA QQ plots- check the Confidence Intervals
- Also for the lowest bound replace 0.00 with 0.01 to reflect the cut-off applied for the plotting

**Comment by pjvandehaar** [comment]
# CI

copy [`get_conf_int()`](https://github.com/statgen/encore/blob/master/plot-epacts-output/make_qq_json.py#L48).

**Comment by pjvandehaar** [comment]
I fixed the QQ in https://github.com/statgen/pheweb/commit/4c109eeaa90c7c04f7d4b88bc96ba7e3773429e8 .  I need to merge that into master.  In order to do that, I need to update some documentation.  I'll do that sometime.

**Comment by sgagliano** [comment]
@pjvandehaar You've merged py3 into master, right? So, this issue can be closed?

**Comment by pjvandehaar** [comment]
I've merge `py3`3, so now the legend is fixed, but I still need to fix the 95% CI.  Hopefully I can finish that this morning.

**Comment by pjvandehaar** [comment]
Now tracked in https://github.com/statgen/pheweb/issues/50
