### ISSUE TITLE
make flexible tooltips for LZ

### ISSUE THREAD

**Issue by pjvandehaar** [statgen/pheweb#27]
### different sets of attributes for each phenotype

LocusZoom requires me to specify which attributes will exist (`layout.panels[#id=association].data_layers[#id=associationpvalues].fields`).  But I want users to be able to use whichever attributes they want.  For now, I'll have a constant set of attributes for each pheweb, but later I'll likely have a different set for each phenotype _within_ a pheweb.

I'd like to skip straight to dynamically setting `fields` for each phenotype.

Options:

1. Know which attributes we have before we serve our javascript, and modify it server-side.

2. On the client, modify things after receiving data.  `.getData(...)` is probably the best place to do that.  Chris didn't like that idea, and I didn't understand why not.  Look into `parseResponse`, especially the one in `GeneSource`.

### tooltips

LocusZoom tooltip templating only allows substituting values, and nothing more complicated.  Different phewebs have different attributes to show.  Soon even different phenotypes within the same pheweb will have different attributes. Later, within a single phenotype, different variants will have different attributes.  (eg, GWAS Catalog hits).  On the LZ-PheWAS, different points have different attributes.

I'd love to just have a function that takes a variant and returns HTML.  What if the tooltip just included an id and `<script>foo(variant)</script>`?

### Conversation with Chris:
-    // just follow the docs at https://github.com/statgen/locuszoom
-    // plot.on('data_rendered', () => { modify this.**.tooltip })
-    // but .fields is gonna be a problem
-    // I could hackishly modify it in the .getData
-    // or I can make the parseResponse &c act more forgiving like in GeneSource.

**Comment by pjvandehaar** [comment]
Figure out how `LZ.DataLayer.updateTooltip` uses `LZ.parseFields(d, template_string)`.  Do I monkeypatch in my own html-generating function, or just extend `parseFields`?

**Comment by Frencil** [comment]
Will `fields` still be a problem given the internalization of the PheWAS data source using flexible field definition/generation implemented in [v0.5.5](https://github.com/statgen/locuszoom/releases/tag/v0.5.5)? I'd  still like to refactor the other data sources (e.g. association) to behave the same way but, for that one especially, it's among the oldest and most entangled with the older and more rigid approach.

**Comment by pjvandehaar** [comment]
I don't know.  I haven't run into problems yet, but I don't understand what's happening.

I'm going to re-write this PR to use an AST.
