### ISSUE TITLE
Make points clickable in LZ

### ISSUE THREAD

**Issue by pjvandehaar** [statgen/pheweb#38]
Understand

- how `LocusZoom.DataLayer.prototype.applyStatusBehavior` works
- where `layout.panels[0].data_layers[1].selected.onclick` is accessed.

**Comment by Frencil** [comment]
FYI I'm actively working on extending LZ to allow for this class of behaviors. Details [here](https://github.com/statgen/locuszoom/issues/84).

**Comment by Frencil** [comment]
FYI this is implemented on master in LZ but there's a bit more cleanup work to do and I'd like to bundle it with the other recent changes into a proper release. I'll let you know when [0.5.4](https://github.com/statgen/locuszoom/releases/tag/v0.5.4) is ready to go; it should be sometime this week.
