### ISSUE TITLE
Make labels click/hoverable in LZ

### ISSUE THREAD

**Issue by pjvandehaar** [statgen/pheweb#39]

**Comment by Frencil** [comment]
@pjvh can you expand on this? What should the hover/click action be when applied to a label? Should it just extend whatever hover/click actions are on the element it's attached to, or do you envision something different?

**Comment by pjvandehaar** [comment]
Yes, when a label is clicked/hovered, it should be exactly like the point was clicked/hovered.  I'd like to have the behavior that <http://pheweb.sph.umich.edu/variant/22-44324727-C-G> has right now.

**Comment by pjvandehaar** [comment]
On the new version of LZ this is working, but it has a problem:  when the label and tooltip both extend from a point in the same direction, then when you hover the label, the tooltip pops up, meaning that now you're on the tooltip, not the label, and so the tooltip goes away, and you get a nasty cycle (limited to one show/hide per pixel the mouse moves).

(Old-PheWAS didn't have this problem because the tooltips were always above the points, and labels always beside.)

We need to keep the current behavior that hovering a tooltip has no effect.

*Option 1*: when you hover a label, the tooltip avoids the label.  But if a point is near the bottom-left corner, and the label goes straight right, then what?  We can't move the label.  Where's the tooltip supposed to go?  Tooltips don't know how to go above/below points, and they certainly don't know how to extend further away from a point.  But if they could go up/down, and lengthen the connecting triangle, and would avoid the label when they popped up, that would solve this problem, right?

*Option 2*: When the tooltip pops up, you're still hovering it, even though you can't see it.  ie, tooltips are invisible from the mouse's perspective.  Look into <http://stackoverflow.com/questions/1401658/html-overlay-which-allows-clicks-to-fall-through-to-elements-behind-it>.

**Comment by Frencil** [comment]
Tooltips actually do know how to go above/below points, as well as in jsut about any other configuration (see genes and interval data layers for vertical tool tip positioning).

Each data layer implements its own tool tip positioning method, and the abstract data layer class has a naive positioning function that just hangs all tool tips off the bottom right.

The simplest approach using what's already in the library would be to adopt the vertical positioning logic, which would mean overriding the defined `positionTooltip` method on the scatter data layer. This can be made more robust by having scatter know how to do both vertical *or* horizontal positioning and then let a new layout directive (e.g. `tooltip_positioning` or something) set the behavior, with horizontal (the current mode) being default. This will avoid breaking existing LZ scatter implementations in the wild while safely expanding the capability of the scatter layer.

**Comment by Frencil** [comment]
Update: [latest commit on master](https://github.com/statgen/locuszoom/commit/f0268c8048a847d437dd3c9473f4081c2b209666) implements the change I just suggested. The PheWAS scatter data layer layout is also updated to specify vertical positioning on tool tips, and thus the PheWAS scatter example shows this in action.

It's not a perfect solution, but so long as labels are positioned horizontally this seems to greatly alleviate the competing mouseover space issue.

**Comment by pjvandehaar** [comment]
I added 
```
.lz-data_layer-tooltip {
    pointer-events: none !important; // not sure whether 
}
```

as recommended [here](http://stackoverflow.com/a/3538639/1166306), and it works great in Chrome/Safari/Firefox (haven't tested IE/Edge).  Should LZ expose an option to make tooltips non-hoverable?  Or should that be the default when `behaviors: {click: [{action:'set', status:'selected'}]}` is not there?
