### ISSUE TITLE
Make Consortia-PheWeb

### ISSUE THREAD

**Issue by pjvandehaar** [statgen/pheweb#43]
Ryan has a sqlite3 db that maps rsid <-> cpra.  He also has a table mapping old rsids to current ones.  Use those to fix up association files that are missing some cpras.

### Then:

- use it on Daniel's copy of Christian's data

**Comment by sgagliano** [comment]
For association results with rsID only, add a script to map the variants to chr:bp (b37).

**Comment by dtaliun** [comment]
What about REF/ALT allele when mapping from rsID?

**Comment by sgagliano** [comment]
Looks like all the sum stats with only rsIDs that we have contain list A1 and A2.

**Comment by dtaliun** [comment]
Knowing rsID, A1 (i guess this is effect/coding allele), A2(this is non-effect/non-coding allele) is it possible to map to chr:bp_ref/alt?
