### ISSUE TITLE
Update pheweb's version for each commit

### ISSUE THREAD

**Issue by pjvandehaar** [statgen/pheweb#47]
`version` should always get incremented and end with `-{$(git rev-parse --short -q HEAD)}`.

### Option 1:
Add a `.git/hooks/pre-commit` hook that updates `pheweb/version.py`.

### Option 2:
make `pheweb _r` update `pheweb/version.py` (so that I don't have to install the hook everywhere).  Neither of these need to be robust, because I'm the only one who will use them.

**Comment by pjvandehaar** [comment]
Nah.

**Comment by Frencil** [comment]
Heh. Yeah, every commit would be excessive. However one habit that might be worth considering is tagging the commits the do mark version changes (even just major/minor version bumps) and pushing those tags up to git hub so you get a nice release log for posterity (see [LocusZoom's releases page](https://github.com/statgen/locuszoom/releases) as an example)

**Comment by pjvandehaar** [comment]
I like that idea– then I wouldn't need to keep `master` release-worthy.  Thanks.
