### ISSUE TITLE
Add toolbar button "Choose LD reference"

### ISSUE THREAD

**Issue by pjvandehaar** [statgen/pheweb#58]
When the button is clicked, I'll have to modify the behavior of `datalayer.behaviors.onclick`.  I'll need to make a new `action` named `set_LDref`.

For reference, setting LDref can be done with: `LocusZoom.getToolTipDataLayer(this).makeLDReference(LocusZoom.getToolTipData(this))`

To get the behavior back to follow-link, I'll need another toolbar button.

**Comment by pjvandehaar** [comment]
What will be the UI for conditional analysis?  Just a toolbar button "Condition on this variant", and then the new top hit is selected as the new LD reference?

**Comment by Frencil** [comment]
> What will be the UI for conditional analysis?

If it's useful take a look at [the covariates model menu example](http://statgen.github.io/locuszoom/examples/covariates_model.html) for LocusZoom. This was prototyped out for the T2D portal to do multivariate conditional analysis.

The implementation of the button and menu is as an element in a LocusZoom Dashboard (thus it uses some scaffolding to make the definition more extensible). If this is close to what PheWeb needs but not a perfect fit see the definition [here](https://github.com/statgen/locuszoom/blob/master/assets/js/app/Dashboard.js#L803)... I can help to come up with a modified Dashboard component that PheWeb can add (or can live in the LZ lib, whatever  makes sense).

**Comment by pjvandehaar** [comment]
Yes, that's great how that works with the dashboard.  In that dropdown, I think I'll add a button "select a variant to condition on", and then the user will click a variant, and LZ will switch back to points being links.
