### ISSUE TITLE
use Sardinia-specific LD

### ISSUE THREAD

**Issue by sgagliano** [statgen/pheweb#70]
SardiNIA LD pairwise (r2>0.4) here: `/net/wonderland/home/csidore/Epacts_vcfs/SS3514/LD_tabs/chr*.ld.gz`

**Comment by pjvandehaar** [comment]
I see 
```
10      61321   10:61321_SNP    10      112408444       10:112408444_SNP        0.499858
```
in one of those files.  Is it normal to see LD across 100Mbp?

**Comment by dtaliun** [comment]
Yes, it can be simply by chance.

**Comment by pjvandehaar** [comment]
(Is there a better panel than 1000g to use by default?)

**Comment by abecasis** [comment]
I don't think so.

There's some cool fancy stuff we could do to automatically deduce LD panel, if you are interested.

G
