### ISSUE TITLE
Should we overshadow/replace the PheWAS scatterplot with a top-phenos table and LZ-region?

### ISSUE THREAD

**Issue by pjvandehaar** [statgen/pheweb#74]
1. When I search for a SNP, I'm often interested in seeing the 500kb around that SNP in that SNP's most associated phenotype.

2. Most SNPs have fewer than ten associated phenotypes, for which a table (or forest plot) works well.

Changes I would like:
- when a row in the table is clicked, show a 400kb LZ-region with the current variant as the LD-reference-variant.
- by default show the LZ-region for the top phenotype.
- make the p-value and effect size (esp it's 95% confint lower bound) more visual in the table, like a forest-plot.
- figure out why the table is visually displeasing and fix it.
- instead of paging the table, allow it to grow.  ie, instead of [1-10, 11-20, ...] you choose [1-10, 1-20, 1-40, 1-80].
- shorten or hide the PheWAS plot, especially if there are few associated phenotypes.

**Comment by sgagliano** [comment]
@pjvandehaar I think a plot is nearly always better than a table (at least for visual appeal).
