### ISSUE TITLE
pheweb.sph.umich.edu/<dataset>/<route>

### ISSUE THREAD

**Issue by pjvandehaar** [statgen/pheweb#85]
Todo:
- make PheWeb accept `pheweb serve --urlprefix /UKBiobank`.
- deal with Apache routing (like `gvs`)
- backport that change to HUNT (and run it from `/var/pheweb-installs/HUNT/venv/bin/pheweb serve --urlprefix /HUNT --port 9XXX`)
- backport that change to sardinia  (and run it from `/var/pheweb-installs/HUNT/venv/bin/pheweb serve --urlprefix /sard_quant --port 9XXX`)
- backport that change to mgi-icd9  (and run it from `/var/pheweb-installs/HUNT/venv/bin/pheweb serve --urlprefix /MGI --port 9XXX`)
    - LATER: reload on latest `master`
- make scripts like `/etc/init/gunicorn-topmed-freeze3a-grch37.conf` for each.
- apache forward `/pheno/.*` -> `/MGI/pheno/$1`.

---

- option 1: use [blueprints](http://flask.pocoo.org/docs/0.12/blueprints/).

- option 2: make a `pheweb-manager` which fetches `app` from each pheweb-dataset and combines them using [DispatcherMiddleware](http://werkzeug.pocoo.org/docs/0.12/middlewares/#werkzeug.wsgi.DispatcherMiddleware) ("working at the WSGI level") and some of its own static pages and 301 redirects.

- option 3: use [`app.config['APPLICATION_ROOT']`](https://stackoverflow.com/questions/18967441/add-a-prefix-to-all-flask-routes)

- Understand how URL-prefixed application roots interact with login (ie, session cookies).  If the session cookie is tied to that URL-prefix, then will API requests to that URL-prefix already have the login credentials?

- Use `url_for` more.  Use `model.url_prefix` for javascript.

- Then what should live at `/`?
    - MVP: definitely links to our 3+ public datasets (with a little description of each?) and maybe the 2+ private.
    - LATER: "meta-pheweb": search for a single gene/variant and see the most-significant traits from all datasets.

- Figure out how to host a single page at `/` (and also a 301 router pointing from `/pheno` -> `/mgi/pheno` &c) without injecting new session cookies that mess up the URL-prefixed application sessions.  Does having a different `app.config['SECRET_KEY']` mean that they won't overlap?

- I'll want different versions of pheweb for the datasets.  That could be do-able by modifying `sys.path` for each dataset's config.

**Comment by sgagliano** [comment]
@pjvandehaar Which of the two options you listed do you prefer?

**Comment by pjvandehaar** [comment]
I will try option 1 first.
