### ISSUE TITLE
Show a table of phenotypes

### ISSUE THREAD

**Issue by pjvandehaar** [statgen/pheweb#95]
Where?

Should it show the best association (pval &c) for each phenotype?

**Comment by abecasis** [comment]
Maybe in the about page. It could include some summaries (# variants, # phenotypes, # queries, LD source, configurable options?) and also a list of phenotypes.

Gonçalo

**Comment by sgagliano** [comment]
I agree that those summaries would be very helpful.

**Comment by pjvandehaar** [comment]
For each pheno,
- id
- displayname
- description
- #cases/controls/samples
- category?
- top variant's chr-pos-ref-alt&rsid
- top variant's p-value

**Comment by abecasis** [comment]
Genomic control also.

G

**Comment by pjvandehaar** [comment]
Added.
